name: CD prod

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cargo login ${{ secrets.CARGO_TOKEN }}
      - run: cargo publish
